### ISSUE TITLE
how to setup?

### ISSUE THREAD

**Issue by thger1312** [california444/homebridge-viessmann-control#152]
i get errors after installing this plugin. how do i found out the right port? do i have to install the vcontrold-plugin too?
ip adress of the homebridge or the heating system/vitoconnect?

**Comment by california444** [comment]
Hi,
thanks for installing the plugin.
It uses the vcontrol daemon. You have to set up the IP address and port under which vcontrol is reachable.
This plugin is made for my individual configuration and setup with two heating circles.
In order to use it you would need to have the same configuration and commands in vcontrol as the plugin expects.
Best
Roman
